language: python

python:
  - 3.5
  - 3.8

sudo: false

install:
  - pip install -r requirements/travis.txt

script:
  - make quality
  - make test

branches:
    only:
      - master

after_success: coveralls
