language: python
python: "2.7"
install:
  - "pip install six"
  - "make install"
sudo: false
script:
  - make quality
  - make test
branches:
    only:
      - master
      - mrehan/convert-lti-to-django-app
after_success: coveralls
